### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by unional**
Re-order overloads and add missing signature. 🌷

### CODE REVIEW

**Comment by blakeembrey** [comment]
I still don't understand this one 😦 I'm assuming it's an implementation bug with Webstorm, since the types are all mutually exclusive.

**Comment by blakeembrey** [comment]
Oh, but LGTM 👍

**Comment by unional** [comment]
Ah, actually it seems to be a bug on the `tsc` that it works today?

`test('string', t => {})` doesn't match any signature! 😜

**Comment by unional** [comment]
Got it. It is because of this:

``` ts
  export interface Options {
    skip?: boolean;
    timeout?: number;
  }
```

`string` actually matches `Options` because all properties are optional...

So the more precise version should be:

``` ts
  export interface Options extends Object {
    skip?: boolean;
    timeout?: number;
  }
```

**Comment by blakeembrey** [comment]
Oh, crazy, yeah - great point. I always forget that quirk. Looks great 👍

**Pull request merged**
